# Change these first
owner: rayker77 # Your GitHub organization or username, where this repository lives
repo: upptimee # The name of this repository

sites:
  - name: GTD Mostazal
    check: "tcp-ping"
    url: 200.126.94.66
    port: 80
  - name: Movistar Mostazal
    check: "tcp-ping"
    url: 200.54.96.124
    port: 53
  - name:Entel Mostazal
    check: "tcp-ping"
    url: 164.77.172.234
    port: 80
  - name: GTD Malloa
    check: "tcp-ping"
    url: 200.126.94.50
    port: 80
  - name: CSTIC Malloa
    check: "tcp-ping"
    url: 45.165.168.4
    port: 80
  - name: Gtd Molina
    check: "tcp-ping"
    url: 200.126.94.34
    port: 80
  - name: Movistar Molina
    check: "tcp-ping"
    url: 200.68.57.58
    port: 80
  - name: Entel Molina
    check: "tcp-ping"
    url: 186.67.50.94
    port: 80

assignees:
  - Rayker77

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  baseUrl: /upptimee
  logoUrl: https://garcesfruit.com/favicon.ico
  favicon: https://garcesfruit.com/favicon.ico
  faviconSvg: https://garcesfruit.com/favicon.ico
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** Sitios corporativos"
  introMessage:
  navbar:
    - title: GarcesFruit
      href: https://garcesfruit.com/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
